name: Execute Eversys Scripts

on:
  schedule:
    - cron: "*/30 * * * *"  # Runs every 30 minutes
  workflow_dispatch:

jobs:
  run-eversys-scripts:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Download Script
        run: python downloadeversysfiles.py
        working-directory: C:\Users\Administrator\DataCycleProject\DataCycleProject_Grp10

      - name: Run Extract Script
        run: python extracteversysdata.py
        working-directory: C:\Users\Administrator\DataCycleProject\DataCycleProject_Grp10

      - name: Run Silver Script
        run: python silvercleaningscript.py
        working-directory: C:\Users\Administrator\DataCycleProject\DataCycleProject_Grp10
