name: Execute Eversys Scripts

on:
  schedule:
   - cron: "*/30 */30 * * *"  # Runs every 30 minutes -- temp: every 30 hours
  workflow_dispatch:

jobs:
  run-eversys-scripts:
    runs-on: [self-hosted]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Run Download Script
        run: python downloadeversysfiles.py

      - name: Run Extract Script
        run: python extracteversysdata.py

      - name : Run Silver Script
        run: python silvercleaningscript.py
