name: Deploy mdBook site to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.36
    steps:
      - uses: actions/checkout@v4
      
      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
          source "$HOME/.cargo/env"
          cargo install mdbook --version ${MDBOOK_VERSION}

      - name: Setup mdBook structure
        run: |
          # Create src directory if it doesn't exist
          mkdir -p src
          
          # Copy README.md to src directory if it exists
          if [ -f README.md ]; then
            cp README.md src/
          else
            # Create a default README.md if it doesn't exist
            echo "# Technical Documentation" > src/README.md
          fi
          
          # Copy SUMMARY.md to src directory
          cp SUMMARY.md src/
          
          # Debug - list directories to see actual structure
          echo "Current directory structure:"
          find . -type f -name "*.md" | sort
          
          # Create directories in src with URL-encoded spaces
          mkdir -p "src/database%20documentation"
          mkdir -p "src/datawarehouse%20documentation"
          mkdir -p "src/knime%20documentation"
          
          # Copy files from Technical_Documentation directly to src
          cp "Technical_Documentation/ETL-Process-Flow.md" src/ || echo "File not found: Technical_Documentation/ETL-Process-Flow.md"
          cp "Technical_Documentation/DB-System-Overview.md" src/ || echo "File not found: Technical_Documentation/DB-System-Overview.md"
          cp "Technical_Documentation/DW-System-Overview.md" src/ || echo "File not found: Technical_Documentation/DW-System-Overview.md"
          cp "Technical_Documentation/Github-Actions-workflows.md" "src/knime%20documentation/" || echo "File not found: Technical_Documentation/Github-Actions-workflows.md"
          
          # Copy database documentation files
          cp "Technical_Documentation/database documentation/DB-ETL-Process.md" "src/database%20documentation/" || echo "File not found: Technical_Documentation/database documentation/DB-ETL-Process.md"
          cp "Technical_Documentation/database documentation/DB-Import-Setup-Guide.md" "src/database%20documentation/" || echo "File not found: Technical_Documentation/database documentation/DB-Import-Setup-Guide.md"
          cp "Technical_Documentation/database documentation/DB-Schema.md" "src/database%20documentation/" || echo "File not found: Technical_Documentation/database documentation/DB-Schema.md"
          cp "Technical_Documentation/database documentation/DB-SQL-Server-Agent-Jobs.md" "src/database%20documentation/" || echo "File not found: Technical_Documentation/database documentation/DB-SQL-Server-Agent-Jobs.md"
          cp "Technical_Documentation/database documentation/DB-Stored-Procedures.md" "src/database%20documentation/" || echo "File not found: Technical_Documentation/database documentation/DB-Stored-Procedures.md"
          
          # Copy datawarehouse documentation files
          cp "Technical_Documentation/datawarehouse documentation/DW-Dimension-Tables.md" "src/datawarehouse%20documentation/" || echo "File not found: Technical_Documentation/datawarehouse documentation/DW-Dimension-Tables.md"
          cp "Technical_Documentation/datawarehouse documentation/DW-Fact-Tables.md" "src/datawarehouse%20documentation/" || echo "File not found: Technical_Documentation/datawarehouse documentation/DW-Fact-Tables.md"
          cp "Technical_Documentation/datawarehouse documentation/DW-Schema.md" "src/datawarehouse%20documentation/" || echo "File not found: Technical_Documentation/datawarehouse documentation/DW-Schema.md"
          cp "Technical_Documentation/datawarehouse documentation/DW-Stored-Procedures.md" "src/datawarehouse%20documentation/" || echo "File not found: Technical_Documentation/datawarehouse documentation/DW-Stored-Procedures.md"
          
          # Copy knime documentation files
          cp "Technical_Documentation/knime documentation/KNIME_workflows.md" "src/knime%20documentation/" || echo "File not found: Technical_Documentation/knime documentation/KNIME_workflows.md"
          
          # Alternative approach using find command with case insensitivity (-iname) and with spaces in paths
          # This will find files even if case doesn't match exactly
          echo "Trying alternative approach with find command..."
          
          find "Technical_Documentation" -type f -iname "*etl*process*flow*.md" -exec cp {} src/ \; 2>/dev/null || echo "ETL-Process-Flow.md not found with find"
          find "Technical_Documentation" -type f -iname "*db-system*overview*.md" -exec cp {} src/ \; 2>/dev/null || echo "DB-System-Overview.md not found with find"
          find "Technical_Documentation" -type f -iname "*dw-system*overview*.md" -exec cp {} src/ \; 2>/dev/null || echo "DW-System-Overview.md not found with find"
          
          find "Technical_Documentation" -type f -iname "*db-etl*process*.md" -exec cp {} "src/database%20documentation/" \; 2>/dev/null || echo "DB-ETL-Process.md not found with find"
          find "Technical_Documentation" -type f -iname "*db-import*setup*.md" -exec cp {} "src/database%20documentation/" \; 2>/dev/null || echo "DB-Import-Setup-Guide.md not found with find"
          find "Technical_Documentation" -type f -iname "*db-sql*server*.md" -exec cp {} "src/database%20documentation/" \; 2>/dev/null || echo "DB-SQL-Server-Agent-Jobs.md not found with find"
          find "Technical_Documentation" -type f -iname "*db-schema*.md" -exec cp {} "src/database%20documentation/" \; 2>/dev/null || echo "DB-Schema.md not found with find"
          find "Technical_Documentation" -type f -iname "*db-stored*procedures*.md" -exec cp {} "src/database%20documentation/" \; 2>/dev/null || echo "DB-Stored-Procedures.md not found with find"
          
          find "Technical_Documentation" -type f -iname "*dw-dimension*tables*.md" -exec cp {} "src/datawarehouse%20documentation/" \; 2>/dev/null || echo "DW-Dimension-Tables.md not found with find"
          find "Technical_Documentation" -type f -iname "*dw-fact*tables*.md" -exec cp {} "src/datawarehouse%20documentation/" \; 2>/dev/null || echo "DW-Fact-Tables.md not found with find"
          find "Technical_Documentation" -type f -iname "*dw-schema*.md" -exec cp {} "src/datawarehouse%20documentation/" \; 2>/dev/null || echo "DW-Schema.md not found with find"
          find "Technical_Documentation" -type f -iname "*dw-stored*procedures*.md" -exec cp {} "src/datawarehouse%20documentation/" \; 2>/dev/null || echo "DW-Stored-Procedures.md not found with find"
          
          find "Technical_Documentation" -type f -iname "*knime*workflow*.md" -exec cp {} "src/knime%20documentation/" \; 2>/dev/null || echo "KNIME_workflows.md not found with find"
          find "Technical_Documentation" -type f -iname "*github*actions*.md" -exec cp {} "src/knime%20documentation/Github-Actions-workflows.md" \; 2>/dev/null || echo "Github-Actions-workflows.md not found with find"
          
          # Create placeholder files for any missing files
          for file in ETL-Process-Flow.md DB-System-Overview.md DW-System-Overview.md; do
            if [ ! -f "src/$file" ]; then
              echo "# $file\n\nThis documentation is under development." > "src/$file"
              echo "Created placeholder for $file"
            fi
          done
          
          for file in DB-ETL-Process.md DB-Import-Setup-Guide.md DB-SQL-Server-Agent-Jobs.md DB-Schema.md DB-Stored-Procedures.md; do
            if [ ! -f "src/database%20documentation/$file" ]; then
              echo "# $file\n\nThis documentation is under development." > "src/database%20documentation/$file"
              echo "Created placeholder for database%20documentation/$file"
            fi
          done
          
          for file in DW-Dimension-Tables.md DW-Fact-Tables.md DW-Schema.md DW-Stored-Procedures.md; do
            if [ ! -f "src/datawarehouse%20documentation/$file" ]; then
              echo "# $file\n\nThis documentation is under development." > "src/datawarehouse%20documentation/$file"
              echo "Created placeholder for datawarehouse%20documentation/$file"
            fi
          done
          
          for file in KNIME_workflows.md; do
            if [ ! -f "src/knime%20documentation/$file" ]; then
              echo "# $file\n\nThis documentation is under development." > "src/knime%20documentation/$file"
              echo "Created placeholder for knime%20documentation/$file"
            fi
          done
          
          if [ ! -f "src/knime%20documentation/Github-Actions-workflows.md" ]; then
            echo "# Github Actions Workflows\n\nThis documentation is under development." > "src/knime%20documentation/Github-Actions-workflows.md"
            echo "Created placeholder for knime%20documentation/Github-Actions-workflows.md"
          fi
          
          # List all files that were copied to src
          echo "Final src directory structure:"
          find src -type f | sort
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      
      - name: Build with mdBook
        run: mdbook build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4