name: Deploy mdBook site to Pages
on:
  push:
    branches: ["main"]
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: "pages"
  cancel-in-progress: false
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MDBOOK_VERSION: 0.4.36
    steps:
      - uses: actions/checkout@v4
      
      - name: Install mdBook
        run: |
          curl --proto '=https' --tlsv1.2 https://sh.rustup.rs -sSf | sh -s -- -y
          source "$HOME/.cargo/env"
          cargo install mdbook --version ${MDBOOK_VERSION}
      
      - name: Setup mdBook structure
        run: |
          # Create src directory if it doesn't exist
          mkdir -p src
          
          # Copy README.md to src directory if it exists
          if [ -f README.md ]; then
            cp README.md src/
          else
            # Create a default README.md if it doesn't exist
            echo "# Technical Documentation" > src/README.md
          fi
          
          # Copy SUMMARY.md to src directory
          cp SUMMARY.md src/
          
          # Create directories in src
          mkdir -p src/database_documentation
          mkdir -p src/datawarehouse_documentation
          mkdir -p src/knime_documentation
          
          # Copy overview files from root or Technical_Documentation folder
          cp Technical_Documentation/ETL-Process-Flow.md src/ || cp ETL-Process-Flow.md src/ || echo "File not found: ETL-Process-Flow.md"
          cp Technical_Documentation/DB-System-Overview.md src/ || cp DB-System-Overview.md src/ || echo "File not found: DB-System-Overview.md"
          cp Technical_Documentation/DW-System-Overview.md src/ || cp DW-System-Overview.md src/ || echo "File not found: DW-System-Overview.md"
          
          # Copy database documentation files
          cp Technical_Documentation/database_documentation/DB-ETL-Process.md src/database_documentation/ || cp database_documentation/DB-ETL-Process.md src/database_documentation/ || echo "File not found: database_documentation/DB-ETL-Process.md"
          cp Technical_Documentation/database_documentation/DB-Import-Setup-Guide.md src/database_documentation/ || cp database_documentation/DB-Import-Setup-Guide.md src/database_documentation/ || echo "File not found: database_documentation/DB-Import-Setup-Guide.md"
          cp Technical_Documentation/database_documentation/DB-SQL-Server-Agent-Jobs.md src/database_documentation/ || cp database_documentation/DB-SQL-Server-Agent-Jobs.md src/database_documentation/ || echo "File not found: database_documentation/DB-SQL-Server-Agent-Jobs.md"
          cp Technical_Documentation/database_documentation/DB-Schema.md src/database_documentation/ || cp database_documentation/DB-Schema.md src/database_documentation/ || echo "File not found: database_documentation/DB-Schema.md"
          cp Technical_Documentation/database_documentation/DB-Stored-Procedures.md src/database_documentation/ || cp database_documentation/DB-Stored-Procedures.md src/database_documentation/ || echo "File not found: database_documentation/DB-Stored-Procedures.md"
          
          # Copy datawarehouse documentation files
          cp Technical_Documentation/datawarehouse_documentation/DW-Dimension-Tables.md src/datawarehouse_documentation/ || cp datawarehouse_documentation/DW-Dimension-Tables.md src/datawarehouse_documentation/ || echo "File not found: datawarehouse_documentation/DW-Dimension-Tables.md"
          cp Technical_Documentation/datawarehouse_documentation/DW-Fact-Tables.md src/datawarehouse_documentation/ || cp datawarehouse_documentation/DW-Fact-Tables.md src/datawarehouse_documentation/ || echo "File not found: datawarehouse_documentation/DW-Fact-Tables.md"
          cp Technical_Documentation/datawarehouse_documentation/DW-Schema.md src/datawarehouse_documentation/ || cp datawarehouse_documentation/DW-Schema.md src/datawarehouse_documentation/ || echo "File not found: datawarehouse_documentation/DW-Schema.md"
          cp Technical_Documentation/datawarehouse_documentation/DW-Stored-Procedures.md src/datawarehouse_documentation/ || cp datawarehouse_documentation/DW-Stored-Procedures.md src/datawarehouse_documentation/ || echo "File not found: datawarehouse_documentation/DW-Stored-Procedures.md"
          
          # Copy knime documentation files
          cp Technical_Documentation/knime_documentation/KNIME_workflows.md src/knime_documentation/ || cp knime_documentation/KNIME_workflows.md src/knime_documentation/ || echo "File not found: knime_documentation/KNIME_workflows.md"
          
          # Copy GitHub Actions documentation
          cp Technical_Documentation/knime_documentation/Github-Actions-workflows.md src/knime_documentation/ || cp knime_documentation/Github-Actions-workflows.md src/knime_documentation/ || echo "File not found: knime_documentation/Github-Actions-workflows.md"
          
          # Fix case sensitivity issues if needed
          find Technical_Documentation -name "*.md" -type f -exec bash -c 'cp "$0" "src/${0#Technical_Documentation/}"' {} \; 2>/dev/null || echo "No files found in Technical_Documentation"
      
      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v5
      
      - name: Build with mdBook
        run: mdbook build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./book
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
